# Generated by Django 4.0.4 on 2022-05-06 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem_delete_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='admount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 13, 7, 44, 626176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 13, 7, 44, 627175, tzinfo=utc)),
        ),
    ]
