# Generated by Django 4.0.4 on 2022-05-06 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_date_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 14, 28, 4, 695871, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 14, 28, 4, 695871, tzinfo=utc)),
        ),
    ]
